# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ancestry.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61ncestry.proto\x12\x08\x61ncestry\"(\n\nAncestryId\x12\x0b\n\x03val\x18\x01 \x01(\x04\x12\r\n\x05scope\x18\x02 \x01(\x04\"\xb2\x01\n\x0c\x41ltoMetadata\x12*\n\x0c\x61ncestry_tag\x18\x01 \x03(\x0b\x32\x14.ancestry.AncestryId\x12\x0e\n\x06is_eos\x18\x02 \x01(\x08\x12I\n\x1c\x66inished_processing_log_item\x18\x03 \x01(\x0b\x32#.ancestry.FinishedProcessingLogItem\x12\x1b\n\x13sticky_routing_hash\x18\x04 \x01(\x03\"B\n\x0bTextSegment\x12\x0c\n\x04text\x18\x01 \x01(\t\x12%\n\ttext_type\x18\x02 \x01(\x0e\x32\x12.ancestry.TextType\"@\n\x12\x46inishedProcessing\x12\x1b\n\x13incoming_queue_name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x04\"\xa0\x01\n\x19\x46inishedProcessingLogItem\x12\x10\n\x08stage_id\x18\x01 \x01(\x04\x12\x12\n\nreplica_id\x18\x02 \x01(\x04\x12\x39\n\x13\x66inished_processing\x18\x03 \x03(\x0b\x32\x1c.ancestry.FinishedProcessing\x12\"\n\x1arequest_processing_seconds\x18\x04 \x01(\x02*a\n\x08TextType\x12\t\n\x05\x45MPTY\x10\x00\x12\x08\n\x04WORD\x10\x01\x12\x08\n\x04LINE\x10\x02\x12\r\n\tPARAGRAPH\x10\x03\x12\x0c\n\x08SENTENCE\x10\x04\x12\r\n\tFULL_TEXT\x10\x05\x12\n\n\x06\x43USTOM\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ancestry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTTYPE']._serialized_start=548
  _globals['_TEXTTYPE']._serialized_end=645
  _globals['_ANCESTRYID']._serialized_start=28
  _globals['_ANCESTRYID']._serialized_end=68
  _globals['_ALTOMETADATA']._serialized_start=71
  _globals['_ALTOMETADATA']._serialized_end=249
  _globals['_TEXTSEGMENT']._serialized_start=251
  _globals['_TEXTSEGMENT']._serialized_end=317
  _globals['_FINISHEDPROCESSING']._serialized_start=319
  _globals['_FINISHEDPROCESSING']._serialized_end=383
  _globals['_FINISHEDPROCESSINGLOGITEM']._serialized_start=386
  _globals['_FINISHEDPROCESSINGLOGITEM']._serialized_end=546
# @@protoc_insertion_point(module_scope)
